// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectMKVFile() {
  return window['go']['main']['App']['SelectMKVFile']();
}

export function SplitMKV(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitMKV'](arg1, arg2, arg3);
}
