// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectMKVFile():Promise<string>;

export function SplitMKV(arg1:string,arg2:number,arg3:number):Promise<string>;
